print("Aliza Mariz R. rabe")
print("tanza boac Marinduque")
print("July 30,2003")
print("BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY")
print("2ND YEAR")
print(" class-C")
print(" singing")
print(" reading")
print(" dancing")
print(" drawing")
print(" watching")
